export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAINPAGE_ROUTE = '/'
export const RUCHKA_ROUTE = '/Ручки'
export const CHIP_ROUTE = '/Кодовая полоска'
export const DEVICE_ROUTE = '/Плата'
export const PASSPORT_ROUTE = '/Паспорта'